{% set name = "dash-auth" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_auth-{{ version }}.tar.gz
  sha256: 82b9bd6fb82bef28aab4f4bb09989697bfe8779cfb6e7c5523f98a6601646ed7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - dash >=1.1.1
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - dash_auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://plotly.com/dash
  summary: Dash Authorization Package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
